import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("manager office workspace source", () => {
  it("renders a Codex-like office workspace with conversation history and chat", () => {
    const managerSource = readFileSync("src/components/ManagerPage.tsx", "utf8");
    const appSource = readFileSync("src/App.tsx", "utf8");
    const stylesSource = readFileSync("src/styles.css", "utf8");

    expect(managerSource).toContain("manager-app-shell");
    expect(managerSource).toContain("codex-sidebar");
    expect(managerSource).toContain("codex-project-list");
    expect(managerSource).toContain("collapsedProjectIds");
    expect(managerSource).toContain("projectConversations");
    expect(managerSource).toContain("codex-project-conversations");
    expect(managerSource).toContain("onSwitchProject");
    expect(managerSource).toContain("onDeleteProject");
    expect(managerSource).toContain("codex-chat-main");
    expect(managerSource).toContain("activeAgentModel");
    expect(managerSource).toContain("openAiCompatibleModels");
    expect(managerSource).toContain("claudeAgentModels");
    expect(managerSource).toContain("composer-model-picker");
    expect(managerSource).toContain("composer-model-menu");
    expect(managerSource).toContain("modelMenuOpen");
    expect(managerSource).toContain("OpenAI 兼容");
    expect(managerSource).toContain("Claude Agent SDK");
    expect(managerSource).not.toContain("<optgroup");
    expect(managerSource).not.toContain("office-model-header");
    expect(managerSource).not.toContain("office-mode-switch");
    expect(managerSource).not.toContain("switchOfficeProvider");
    expect(managerSource).not.toContain("officeModeOptions");
    expect(managerSource).not.toContain('onCreateConversation("agent")');
    expect(managerSource).toContain('onCreateConversation("chat")');
    expect(managerSource).toContain("codex-conversation-rename");
    expect(managerSource).toContain("onRenameConversation");
    expect(managerSource).toContain("composer-permission-select");
    expect(managerSource).not.toContain('disabled={activeAgentModel?.provider !== "claude-agent"}');
    expect(managerSource).not.toContain("选择 Claude Agent SDK 模型时生效");
    expect(managerSource).toContain("composer-model-select");
    expect(managerSource).toContain("onSendMessage");
    expect(managerSource).toContain("onSendOfficeMessage");
    expect(appSource).toContain("async function sendOfficeMessage");
    expect(appSource).toContain("onSendOfficeMessage={sendOfficeMessage}");
    expect(appSource).toContain("currentProjectConversations");
    expect(appSource).toContain("chatBindingLabel");
    expect(appSource).toContain('currentPetModel?.provider === "claude-agent"');
    expect(appSource).toContain('activeAgentModel?.provider === "claude-agent"');
    expect(appSource).toContain("const officeUsesWorkAgent = Boolean(activeAgentModel)");
    expect(appSource).toContain('const modeForRequest: PetConversationMode = officeUsesWorkAgent ? "agent" : "chat"');
    expect(appSource).toContain("const response = officeUsesWorkAgent");
    expect(appSource).toContain("applyPetActions(petActions, responseSettings)");
    expect(managerSource).toContain("messageListRef");
    expect(managerSource).toContain("sendingOfficeMessage");
    expect(managerSource).toContain("setOfficeElapsedMs");
    expect(managerSource).toContain("pendingOfficeAttachments");
    expect(managerSource).toContain("addOfficeFiles");
    expect(managerSource).toContain("buildAttachmentMessage");
    expect(managerSource).toContain("onDragOver={handleOfficeDragOver}");
    expect(managerSource).toContain("onDrop={(event) => void handleOfficeDrop(event)}");
    expect(managerSource).toContain("message.displayContent ?? message.content");
    expect(managerSource).toContain("setOfficeDraft(\"\")");
    expect(managerSource).toContain("requestAnimationFrame");
    expect(managerSource).toContain("section, activeConversation?.id, messages.length, messages.at(-1)?.content, sendingOfficeMessage, chatError");
    expect(managerSource).toContain("收到，正在处理...");
    expect(managerSource).toContain("scrollTop = messageList.scrollHeight");
    expect(stylesSource).toContain("grid-template-rows: minmax(0, 1fr) auto");
    expect(stylesSource).toContain(".codex-sidebar-nav button");
    expect(managerSource).not.toContain("className=\"model-routing\"");
    expect(appSource).toContain("onSendMessage={sendMessage}");
  });
});
