import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("manager office workspace source", () => {
  it("renders a Codex-like office workspace as the single task entry", () => {
    const managerSource = readFileSync("src/components/ManagerPage.tsx", "utf8");
    const sidebarSource = readFileSync("src/components/ManagerSidebar.tsx", "utf8");
    const appSource = readFileSync("src/App.tsx", "utf8");
    const stylesSource = readFileSync("src/styles.css", "utf8");

    expect(managerSource).toContain("manager-app-shell");
    expect(managerSource).toContain("ManagerSidebar");
    expect(sidebarSource).toContain("codex-sidebar");
    expect(sidebarSource).toContain("codex-project-list");
    expect(managerSource).not.toContain("codex-project-path");
    expect(managerSource).toContain("collapsedProjectIds");
    expect(sidebarSource).toContain("projectConversations");
    expect(sidebarSource).toContain("codex-project-conversations");
    expect(managerSource).toContain("onSwitchProject");
    expect(managerSource).toContain("onDeleteProject");
    expect(managerSource).toContain("codex-chat-main");
    expect(managerSource).toContain("activeAgentModel");
    expect(managerSource).toContain("openAiCompatibleModels");
    expect(managerSource).toContain("claudeAgentModels");
    expect(managerSource).toContain("composer-model-picker");
    expect(managerSource).toContain("composer-model-menu");
    expect(managerSource).toContain("modelMenuOpen");
    expect(managerSource).toContain("OpenAI 兼容");
    expect(managerSource).toContain("Claude Agent SDK");
    expect(managerSource).not.toContain("<optgroup");
    expect(managerSource).not.toContain("office-model-header");
    expect(managerSource).not.toContain("office-mode-switch");
    expect(managerSource).not.toContain("switchOfficeProvider");
    expect(managerSource).not.toContain("officeModeOptions");
    expect(sidebarSource).toContain('onCreateConversation("agent")');
    expect(managerSource).not.toContain('onCreateConversation("chat")');
    expect(managerSource).toContain("codex-conversation-rename");
    expect(managerSource).toContain("onRenameConversation");
    expect(managerSource).toContain("composer-permission-picker");
    expect(managerSource).toContain("permissionMenuOpen");
    expect(managerSource).toContain("channel-route-summary");
    expect(managerSource).not.toContain("默认路由");
    expect(managerSource).not.toContain('disabled={activeAgentModel?.provider !== "claude-agent"}');
    expect(managerSource).not.toContain("选择 Claude Agent SDK 模型时生效");
    expect(managerSource).toContain("composer-model-select");
    expect(managerSource).toContain("onSendOfficeMessage");
    expect(appSource).toContain("async function sendOfficeMessage");
    expect(appSource).toContain("onSendOfficeMessage={sendOfficeMessage}");
    expect(appSource).not.toContain("currentProjectConversations");
    expect(appSource).toContain("petChatBindingLabel");
    expect(appSource).toContain("PetChatBubble");
    expect(appSource).toContain("openPetChat");
    expect(appSource).not.toContain("onClick={openOffice}");
    expect(appSource).toContain('activeAgentModel?.provider === "claude-agent"');
    expect(appSource).toContain("const officeUsesWorkAgent = Boolean(activeAgentModel)");
    expect(appSource).toContain('const modeForRequest: PetConversationMode = requestUsesWorkAgent ? "agent" : "chat"');
    expect(appSource).toContain("const response = requestUsesWorkAgent");
    expect(appSource).toContain("modelIdOverride");
    expect(appSource).toContain("applyPetActions(petActions, responseSettings)");
    expect(appSource).toContain("throw new Error(workspaceMessage)");
    expect(managerSource).toContain("messageListRef");
    expect(managerSource).toContain("sendingOfficeMessage");
    expect(managerSource).toContain("setOfficeElapsedMs");
    expect(managerSource).toContain("pendingOfficeAttachments");
    expect(managerSource).toContain("addOfficeFiles");
    expect(managerSource).toContain("buildAttachmentMessage");
    expect(managerSource).toContain("copyOfficeMessage");
    expect(managerSource).toContain("editOfficeMessage");
    expect(managerSource).toContain("codex-message-frame");
    expect(managerSource).toContain("isLatestMessage");
    expect(managerSource).toContain("message-action-row");
    expect(managerSource).toContain("onCancelMessage");
    expect(managerSource).toContain("lastFailedOfficeMessage");
    expect(managerSource).toContain("officeTask");
    expect(managerSource).toContain("createOfficeTaskState");
    expect(managerSource).toContain("startOfficeTask");
    expect(managerSource).toContain("completeOfficeTask");
    expect(managerSource).toContain("failOfficeTask");
    expect(managerSource).toContain("cancelOfficeTask");
    expect(managerSource).not.toContain("setOfficeTaskStatus");
    expect(managerSource).not.toContain("setActiveOfficeTask");
    expect(managerSource).not.toContain("createTaskCard");
    expect(managerSource).not.toContain("shouldShowTaskCard");
    expect(managerSource).toContain("task-card");
    expect(managerSource).toContain("retryOfficeMessage");
    expect(managerSource).toContain("Square");
    expect(stylesSource).toContain(".message-action-row");
    expect(stylesSource).toContain(".codex-message-frame:hover .message-action-row");
    expect(stylesSource).toContain(".codex-message-frame.latest .message-action-row");
    expect(stylesSource).toContain(".codex-send-button.stop");
    expect(managerSource).toContain("onDragOver={handleOfficeDragOver}");
    expect(managerSource).toContain("onDrop={(event) => void handleOfficeDrop(event)}");
    expect(managerSource).toContain("message.displayContent ?? message.content");
    expect(managerSource).toContain("setOfficeDraft(\"\")");
    expect(managerSource).toContain("requestAnimationFrame");
    expect(managerSource).toContain("section, activeConversation?.id, messages.length, messages.at(-1)?.content, sendingOfficeMessage, chatError");
    expect(managerSource).toContain("收到，正在处理...");
    expect(managerSource).toContain("scrollTop = messageList.scrollHeight");
    expect(stylesSource).toContain("grid-template-rows: minmax(0, 1fr) auto");
    expect(stylesSource).toContain(".codex-sidebar-nav button");
    expect(stylesSource).not.toContain(".codex-project-path");
    expect(managerSource).not.toContain("className=\"model-routing\"");
    expect(appSource).not.toContain("onSendMessage={sendMessage}");
  });
});
